version: "3"

services:
  gw:
    container_name: cbt-gw
    image: cbt-gw:latest
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'POSTGRES_HOST=db'

  db:
    container_name: cbt-db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=cbt'

